import Navbar from '@/components/views/Navbar'
import './globals.css'
import { Sora } from 'next/font/google'
import Wrapper from '@/components/shared/Wrapper'
import Footer from '@/components/Footer'
import TopLabel from '@/components/views/TopLabel'

const inter = Sora({ subsets: ['latin'],
weight:["100","200","300","400","500","600"] })

export const metadata = {
  title: 'Adeel E-commerce',
  description: 'Generated by Adeel Khalid for prectise',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className='overflow-hidden w-screen'>
          <TopLabel/>
          </div>
        <Wrapper>
        <Navbar/>
        {children}
        <Footer/>
        </Wrapper>
        </body>
    </html>
  )
}
